version: "3.9"
services:
  api:
    build: ./api-service
    ports:
      - "5000:80"
  worker:
    build: ./worker-service
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres